### ISSUE TITLE
Week 10 meeting

### ISSUE THREAD

**Issue by hasibayoubi** [hasibayoubi/Project2#15]

**Comment by Ivanw845** [comment]
Meet on zoom to a combination of
1. Scrum Standup (Take 10 minutes total where we go around and everyone updates on their status and requests help.)
2. Review work going ready for closure (Person presenting the work should show j unit testing is done and demonstrate if possible.)
3. Decide on what to do for next weeks cycle.
4. Pair up anyone who needs help.
